FROM node:24-alpine AS base

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN corepack enable

FROM base AS deps

WORKDIR /workspace

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

FROM deps AS builder

WORKDIR /workspace

COPY . .

RUN pnpm nx build docs

FROM base AS runtime

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080

RUN pnpm add -g serve

COPY --from=builder /workspace/dist/apps/docs ./docs

EXPOSE 8080

CMD ["serve", "-s", "./docs", "-l", "8080"]
